workflows:
  default-workflow:
    name: Law Office App Android Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true
    scripts:
      - name: Recreate Android Folder
        script: |
          # حذف مجلد أندرويد القديم المعطوب وعمل واحد جديد نظيف بأحدث إصدار فلاتر
          rm -rf android
          flutter create . --platforms=android
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Build Flutter APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
